#let p1339-original-metadata = metadata
#let metadata(value) = { assert(json.encode(value, pretty: false) == "{\"main\":{\"strong\":[{\"func\":\"strong\",\"body\":\"sequence([outer], [ ], strong(body: [inner]))\",\"fields\":\"(\\n  delta: 300,\\n  body: sequence([outer], [ ], strong(body: [inner])),\\n  label: <outer-s>,\\n)\",\"label\":\"<outer-s>\",\"delta\":300},{\"func\":\"strong\",\"body\":\"[inner]\",\"fields\":\"(delta: 300, body: [inner], label: <inner-s>)\",\"label\":\"<inner-s>\",\"delta\":300}],\"emph\":[{\"func\":\"emph\",\"body\":\"[inner]\",\"fields\":\"(body: [inner], label: <inner-e>)\",\"label\":\"<inner-e>\",\"delta\":\"absent\"}],\"ordered\":[{\"func\":\"strong\",\"body\":\"sequence([outer], [ ], strong(body: [inner]))\",\"fields\":\"(\\n  delta: 300,\\n  body: sequence([outer], [ ], strong(body: [inner])),\\n  label: <outer-s>,\\n)\",\"label\":\"<outer-s>\",\"delta\":300},{\"func\":\"strong\",\"body\":\"[inner]\",\"fields\":\"(delta: 300, body: [inner], label: <inner-s>)\",\"label\":\"<inner-s>\",\"delta\":300},{\"func\":\"emph\",\"body\":\"[inner]\",\"fields\":\"(body: [inner], label: <inner-e>)\",\"label\":\"<inner-e>\",\"delta\":\"absent\"}],\"strong_empty\":2,\"emph_empty\":1,\"strong_default\":[\"sequence([outer], [ ], strong(body: [inner]))\",\"[inner]\"],\"strong_zero\":[],\"strong_custom\":[],\"strong_body\":[\"[inner]\"],\"emph_body\":[\"[inner]\"]},\"labels\":{\"label_direct\":[{\"func\":\"strong\",\"body\":\"[inner]\",\"fields\":\"(delta: 300, body: [inner], label: <inner-s>)\",\"label\":\"<inner-s>\",\"delta\":300}],\"strong_labeled\":[{\"func\":\"strong\",\"body\":\"[inner]\",\"fields\":\"(delta: 300, body: [inner], label: <inner-s>)\",\"label\":\"<inner-s>\",\"delta\":300}],\"wrong_label\":0}}"); p1339-original-metadata(value) }
#strong[outer #strong[inner]<inner-s>]<outer-s> #emph[inner]<inner-e>
#context metadata((main: (strong: query(strong.where()).map(it => (func: repr(it.func()), body: repr(it.body),
    fields: repr(it.fields()), label: repr(it.at("label", default: none)),
    delta: it.at("delta", default: "absent"))),
    emph: query(emph.where()).map(it => (func: repr(it.func()), body: repr(it.body),
    fields: repr(it.fields()), label: repr(it.at("label", default: none)),
    delta: it.at("delta", default: "absent"))),
    ordered: query(selector(strong.where()).or(emph.where())).map(it => (func: repr(it.func()), body: repr(it.body),
    fields: repr(it.fields()), label: repr(it.at("label", default: none)),
    delta: it.at("delta", default: "absent"))),
    strong_empty: query(strong.where()).len(),
    emph_empty: query(emph.where()).len(),
    strong_default: query(strong.where(delta: 300)).map(it => repr(it.body)),
    strong_zero: query(strong.where(delta: 0)).map(it => repr(it.body)),
    strong_custom: query(strong.where(delta: 100)).map(it => repr(it.body)),
    strong_body: query(strong.where(body: [inner])).map(it => repr(it.body)),
    emph_body: query(emph.where(body: [inner])).map(it => repr(it.body))), labels: (label_direct: query(<inner-s>).map(it => (func: repr(it.func()), body: repr(it.body),
    fields: repr(it.fields()), label: repr(it.at("label", default: none)),
    delta: it.at("delta", default: "absent"))),
    strong_labeled: query(strong.where(label: <inner-s>)).map(it => (func: repr(it.func()), body: repr(it.body),
    fields: repr(it.fields()), label: repr(it.at("label", default: none)),
    delta: it.at("delta", default: "absent"))),
    wrong_label: query(strong.where(label: <inner-e>)).len())))
