"""Assemble provenance of adversarial executions; never issue eligibility or a seal."""
import argparse
import datetime
import hashlib
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
D = ROOT / '00_nucleo/diagnosticos'
AREA = pathlib.Path('/tmp/p1339-mutants.oPfqdA')

def sha(p):
    return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()

def ref(p):
    p = pathlib.Path(p)
    return {'path':str(p), 'sha256':sha(p)}

def source_inventory(base):
    return {str(p.relative_to(base)):sha(p) for p in sorted(base.rglob('*'))
            if p.is_file() and (p.suffix == '.rs' or p.name in ('Cargo.toml','Cargo.lock'))}

def excerpt(base, path, first, last):
    p = base/path
    lines = p.read_text().splitlines()
    return {**ref(p),'first_line':first,'last_line':last,
            'lines':[{'line':n,'text':lines[n-1]} for n in range(first,last+1)]}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--contract',required=True)
    ap.add_argument('--contract-sha256',required=True)
    ap.add_argument('--design',required=True)
    ap.add_argument('--design-sha256',required=True)
    ap.add_argument('--focal',required=True)
    args = ap.parse_args()
    contract_path = D/args.contract
    design_path = D/args.design
    assert sha(contract_path) == args.contract_sha256
    assert sha(design_path) == args.design_sha256
    output = D/'p1339-mutation-registry.json'
    assert not output.exists()
    contract = json.loads(contract_path.read_text())
    negatives = json.loads((D/'p1339-negative-oracles.json').read_text())
    multiplex = json.loads((D/'p1339-mutant-build-multiplex-r4.json').read_text())
    architecture = json.loads((D/'p1339-mutant-build-architecture-pure-r1.json').read_text())
    pure_build = json.loads((D/'p1339-mutant-build-pure-control-r1.json').read_text())
    assert multiplex['exit'] == architecture['exit'] == pure_build['exit'] == 0
    for build in (multiplex,architecture,pure_build):
        assert sha(build['binary']['path']) == build['binary']['sha256']
        assert source_inventory(pathlib.Path(build['source_root'])) == build['source_sha256']
    focal_path = D/args.focal
    focal = json.loads(focal_path.read_text())
    assert focal['negative_oracles_sha256'] == sha(D/'p1339-negative-oracles.json')
    assert len(focal['rows']) == 81
    sources = {
        1:('layout/angle.rs',[145,157]), 2:('layout/angle.rs',[148]),
        3:('foundations/value.rs',[159]), 4:('foundations/ops.rs',[423]),
        5:('foundations/float.rs',[117]), 6:('foundations/float.rs',[120]),
        7:('foundations/float.rs',[146,199]), 8:('foundations/float.rs',[154]),
        9:('foundations/float.rs',[198]), 10:('foundations/float.rs',[218]),
        11:('foundations/float.rs',[114]), 13:('foundations/func.rs',[373]),
        14:('foundations/func.rs',[437]), 15:('foundations/func.rs',[456]),
        16:('../typst-eval/src/call.rs',[58]), 17:('foundations/version.rs',[120]),
        18:('foundations/args.rs',[260]), 19:('foundations/value.rs',[162]),
        20:('foundations/float.rs',[111]),
    }
    causes = {
        1:'Swap both public angle conversion bodies.',
        2:'Use degree scale for the radian conversion.',
        3:'Return finite Float(1) for Float type inf field.',
        4:'Make two Float NaNs compare equal.',
        5:'Map either signed zero to positive one in signum.',
        6:'Map NaN signum to zero.',
        7:'Invert endian selection in each byte conversion direction.',
        8:'Return zero for byte lengths other than four or eight.',
        9:'Force requested byte size to eight.',
        10:'Project generated bytes to Value::Array instead of Bytes.',
        11:'Keep public signum discovery but replace invocation with constant zero.',
        12:'Retain common validation then use a second independent degree formula for bound Angle.deg.',
        13:'Merge new call arguments before With prearguments.',
        14:'Promote a closure to Heading native element for where.',
        15:'Discard where selector named fields.',
        16:'Overwrite explicit static Version.at index with zero; bound path unchanged.',
        17:'Pad negative version indices below explicit length with zero.',
        18:'Accept leftover named arguments in Args.finish.',
        19:'Replace protected selector.before field with a float value.',
        20:'Genuinely abort the signum native callback; retain process signal and raw channels.',
    }
    entries = []
    for case, family in zip(negatives['cases'],contract['mutation_protocol']['families']):
        n = case['family']
        assert family['id'] == f'M{n:02d}'
        build = architecture if n == 12 else multiplex
        rows = [i for i,r in enumerate(focal['rows']) if r['family'] == n]
        assert len(rows) == 4
        mutant = focal['rows'][rows[-1]]
        assert mutant['role'] == 'mutant' and mutant['binary_sha256'] == build['binary']['sha256']
        if n == 12:
            source = AREA/'architecture-negative/crates/typst-eval/src/call.rs'
            lines = [60,73,175]
        elif n == 16:
            source = AREA/'instrumented/crates/typst-eval/src/call.rs'
            lines = sources[n][1]
        else:
            relative,lines = sources[n]
            source = AREA/'instrumented/crates/typst-library/src'/relative
        entries.append({
            'id':family['id'],'required_family':family,'single_cause':causes[n],
            'host':'isolated ratified vanilla source copy, not crystalline candidate',
            'binary':build['binary'],'mode':0 if n == 12 else n,
            'environment':{'P1339_MUTANT':'0' if n == 12 else str(n)},
            'source':{**ref(source),'cause_lines':lines},
            'build':ref(D/('p1339-mutant-build-architecture-pure-r1.json' if n == 12 else 'p1339-mutant-build-multiplex-r4.json')),
            'patch':ref(D/('p1339-mutant-architecture-pure-r1.patch' if n == 12 else 'p1339-mutant-multiplex-r4.patch')),
            'focal_case_id':case['id'],'focal_source_sha256':hashlib.sha256(case['expr'].encode()).hexdigest(),
            'raw_observations':{**ref(focal_path),'zero_based_row_indices':rows},
            'observed_execution':{'exit':mutant.get('exit'),'signal':mutant.get('signal'),'transport':mutant['transport']},
            'eligibility_verdict':None,'discrimination_verdict':None,
            'specific_requirement':('Source/configuration/effective-call-graph witness required; runtime equality not enough.' if n == 12 else
                                    'Raw abnormal execution remains Unknown; verifier tests mandatory_unknown rejection, never preservation credit.' if n == 20 else
                                    'Verifier compares executed observable with the same frozen expression on control/reference.'),
        })
    pure = AREA/'reference'
    negative = AREA/'architecture-negative'
    pure_inventory = source_inventory(pure)
    assert pure_inventory == pure_build['source_sha256']
    changed = [p for p,h in architecture['source_sha256'].items() if pure_inventory.get(p) != h]
    assert changed == ['crates/typst-eval/src/call.rs']
    architecture_witness = {
        'property':'Two effective semantic formula definitions can agree blackbox while violating shared cause.',
        'control':{'source_root':str(pure),'source_sha256':pure_inventory,
                   'binary':pure_build['binary'],
                   'build':ref(D/'p1339-mutant-build-pure-control-r1.json'),
                   'focal_warmup_binary':ref(AREA/'binaries/typst-uninstrumented'),
                   'focal_warmup_sha_matches_final_rebuild':sha(AREA/'binaries/typst-uninstrumented') == pure_build['binary']['sha256']},
        'negative':{'source_root':str(negative),'source_sha256':architecture['source_sha256'],
                    'binary':architecture['binary'],'build':ref(D/'p1339-mutant-build-architecture-pure-r1.json')},
        'changed_source_files':changed,
        'control_shared_cause_edges':[
            'eval_field_callee: Angle target resolves target.ty().scope().get(deg); Type(Angle) resolves Type field scope.',
            'Static Func and bound Method both call call_func; bound inserts receiver as the first argument.',
            'scope macro registers Angle::to_deg_data with parent Angle; func macro closure invokes Angle::to_deg after parsing and finish.',
            'Angle::to_deg calls Angle::to_unit(Deg); to_unit divides to_raw() by AngleUnit::raw_scale, with Deg => PI/180.',
        ],
        'negative_effective_edge':'For bound Angle target and deg field only, successful call_func validation is followed by p1339_duplicate_angle_degrees; that function independently divides angle.to_raw() by PI/180. Static remains original owner.',
        'source_excerpts':[
            excerpt(pure,'crates/typst-eval/src/call.rs',52,70),
            excerpt(pure,'crates/typst-eval/src/call.rs',249,270),
            excerpt(pure,'crates/typst-eval/src/call.rs',166,172),
            excerpt(pure,'crates/typst-library/src/foundations/value.rs',155,168),
            excerpt(pure,'crates/typst-library/src/foundations/ty.rs',118,135),
            excerpt(pure,'crates/typst-macros/src/scope.rs',159,182),
            excerpt(pure,'crates/typst-macros/src/func.rs',389,421),
            excerpt(pure,'crates/typst-library/src/layout/angle.rs',59,66),
            excerpt(pure,'crates/typst-library/src/layout/angle.rs',141,153),
            excerpt(pure,'crates/typst-library/src/layout/angle.rs',248,254),
            excerpt(negative,'crates/typst-eval/src/call.rs',60,76),
            excerpt(negative,'crates/typst-eval/src/call.rs',172,178),
        ],
        'configuration_policy':'Both builds use release lto=false/codegen-units=16 and locked/offline Cargo. Negative has a fresh distinct target; source/config and effective graph determine architecture, not binary SHA inequality alone.',
        'interpretation_owner':'independent verifier; these source edges are adversarial witness inputs, not an eligibility verdict',
    }
    provenance = {}
    for name, argv in {
        'head':['git','rev-parse','HEAD'],
        'working_tree':['git','status','--porcelain','--untracked-files=all','--','.',':(exclude)00_nucleo/materialization',':(exclude)00_nucleo/context'],
        'tracked_diff_stat':['git','diff','HEAD','--stat','--','.',':(exclude)00_nucleo/materialization',':(exclude)00_nucleo/context'],
    }.items():
        p = subprocess.run(argv,cwd=ROOT,capture_output=True,text=True)
        assert p.returncode == 0
        provenance[name] = {'argv':argv,'exit':p.returncode,'stdout':p.stdout,'stderr':p.stderr}
    historical = [p for p in sorted(D.glob('p1339-mutant-*')) if p.is_file() and p != pathlib.Path(__file__)]
    record = {
        'schema':'p1339-adversarial-mutation-registry-v1',
        'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),
        'status':'compiled and focally observed inputs for independent verification; not a seal',
        'executor':'/root/p1336_tests','role':'adversary only',
        'isolation':'procedural only; executado sem atestação de isolamento',
        'inherited_context':'P1336 independent tests and adversarial coordination; P1339 baseline sources permitted; no P1339 candidate exists or was read.',
        'contract':ref(contract_path),'contract_design':ref(design_path),
        'authority_manifest':ref(D/'p1339-authority-manifest-r2.json'),
        'l0_freeze':ref(D/'p1339-l0-freeze.json'),
        'negative_oracles':ref(D/'p1339-negative-oracles.json'),
        'negative_design_ancestry':'Negative focal cases were frozen against pre-canonical design 6a2c2ce5c960d9886fef0c9f8e69b81b76edd34737c0cd3286d082df88d4c90c; historical not-compiled/not-eligible statements describe that time, not final execution. No focal expectations were changed.',
        'pinned_reference':ref('/usr/local/bin/typst'),
        'ratified_reference_commit':'a51e02804','provenance':provenance,
        'multiplex':{'binary':multiplex['binary'],'source_root':multiplex['source_root'],
                     'source_sha256':multiplex['source_sha256'],
                     'selector':excerpt(AREA/'instrumented','crates/typst-library/src/lib.rs',14,25),
                     'mode0':'No semantic mutation active. Positive-base equality over full contract remains an independent verifier gate.',
                     'exclusivity':'Single parsed integer selector; equality predicate per family, no fixture or expected-result lookup.',
                     'excluded_mode12':'Mode12 is rejected; architecture negative is physically absent from this compilation.',
                     'invalid_mode_raw':{**ref(focal_path),'zero_based_row_index':80}},
        'mutants':entries,'architecture_witness':architecture_witness,
        'focal_runner':ref(D/'p1339-mutant-probe.py'),'final_focal':ref(focal_path),
        'source_write_boundary':['isolated /tmp/p1339-mutants.oPfqdA','diagnosticos/p1339-negative-oracles.json','diagnosticos/p1339-mutation-registry.json','diagnosticos/p1339-mutant-*'],
        'measurement_limits':[
            'Focal probes do not establish full contract/profile/order control equivalence or seal.',
            'Initial pure-reference warmup preserved complete tool output chunks and exact argv but did not capture exact UTC start; no timestamp was invented. Fresh pure-control-r1 successor has prospective source/configuration hashes and exact UTC. Later builds and all focal runs have exact UTC intervals.',
            'Inherited host environment is documented with explicit semantic deltas; no environment isolation attestation.',
            'Source graph excerpts and successful builds require independent semantic interpretation; unresolved macro edges must not be accepted silently.',
        ],
        'history':{
            'compile_failures':{'multiplex-r1':'Wrong NativeElement associated item corrected to ELEM.',
                                'multiplex-r2':'EcoVec mutation requires make_mut before get_mut.'},
            'retired_attempts':{'multiplex-r3':'Signum callback resolved inherent f64 method; four modes had no observable gain. Final r4 uses explicit Rust name p1339_signum with unchanged public name signum.',
                                'duplicate-r1':'Cargo cached an unchanged binary; not a valid architecture negative.',
                                'duplicate-r2':'Real compiled separate formula based on multiplex snapshot; superseded by pure-reference-parent M12 to remove physical control ambiguity.'},
            'expectation_revisions':0,'complete_preseal_runs_by_adversary':0,
            'artifacts':[ref(p) for p in historical],
        },
        'registry_builder':ref(__file__),
        'no_claims':['no eligibility verdict','no discrimination verdict','no mutation score','no seal','no candidate implementation','no production source edits','no general Typst equivalence'],
    }
    with output.open('x') as f:
        json.dump(record,f,ensure_ascii=False,indent=2)
        f.write('\n')
    print(json.dumps({'output':str(output),'sha256':sha(output),'compiled_families':len(entries),'verdict':None}))

if __name__ == '__main__':
    main()
