//! Crystalline Lineage
//! @prompt 00_nucleo/prompts/entities/mod.md
//! @prompt-hash ae4f38b6
//! @layer L1
//! @updated 2026-03-22

pub mod file_id;
pub mod font_book;
pub mod math_class;
pub mod operators;
pub mod package_spec;
pub mod span;
pub mod syntax_kind;
pub mod syntax_mode;
pub mod syntax_node;
pub mod syntax_set;
pub mod syntax_text;
pub mod ast;
pub mod module;
pub mod source;
pub mod source_result;
pub mod scope;
pub mod args;
pub mod content;
pub mod func;
pub mod layout_types;
pub mod style_chain;
pub mod value;
pub mod world_types;
