//! Crystalline Lineage
//! @prompt 00_nucleo/prompts/entities/mod.md
//! @prompt-hash a24fe5a6
//! @layer L1
//! @updated 2026-04-30

pub mod file_id;
pub mod font_book;
pub mod math_class;
pub mod operators;
pub mod package_spec;
pub mod span;
pub mod syntax_kind;
pub mod syntax_mode;
pub mod syntax_node;
pub mod syntax_set;
pub mod syntax_text;
pub mod ast;
pub mod module;
pub mod source;
pub mod source_result;
pub mod scope;
pub mod args;
pub mod bib_entry;
pub mod bib_store;
pub mod resolved_label_store;
pub mod citation_form;
pub mod content;
pub mod dir;
pub mod parity;
pub mod sides;
pub mod counter_state_legacy;
pub mod counter_update;
pub mod counter_registry;
pub mod layouter_runtime_state;
pub mod content_hash;
pub mod element_info;
pub mod element_kind;
pub mod element_payload;
pub mod introspector;
pub mod label_registry;
pub mod metadata_store;
pub mod selector;
pub mod state_registry;
pub mod state_update;
pub mod location;
pub mod locator;
pub mod tag;
pub mod engine;
pub mod label;
pub mod func;
pub mod lang;
pub mod font_list;
pub mod glyph_variants;
pub mod layout_types;
pub mod math_constants;
pub mod show;
pub mod sink;
pub mod style;
pub mod style_chain;
pub mod image_sizer;
pub mod geometry;
pub mod ptr_eq_arc;
pub mod value;
pub mod world_types;
