[package]
name = "p1140-inventory"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
typst.workspace = true
typst-bundle.workspace = true
typst-html.workspace = true
typst-pdf.workspace = true
typst-render.workspace = true
typst-svg.workspace = true

[lints]
workspace = true
